name: Coverage Badge

on:
  push:
    branches: [ main ]

jobs:
  update-coverage-badge:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Generate Coverage Badge
        run: npm run coverage:badge
      - name: Commit Badge (if changed)
        run: |
          if git diff --quiet coverage-badge.svg; then
            echo "No badge change";
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add coverage-badge.svg
            git commit -m "chore: update coverage badge [skip ci]"
            git push
          fi
