name: Size Badge
concurrency:
  group: badge-updates
  cancel-in-progress: false
permissions:
  contents: write

on:
  push:
    branches: [ main ]

jobs:
  update-size-badge:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Generate Size Badge
        run: npm run size:badge
      - name: Commit Badge (if changed)
        run: |
          if git diff --quiet size-badge.svg; then
            echo "No size badge change";
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git fetch origin main
            git pull --rebase origin main || true
            git add size-badge.svg
            git commit -m "chore: update size badge [skip ci]"
            for i in 1 2 3; do
              if git push; then echo "Pushed badge update"; break; fi;
              echo "Push failed (attempt $i), retrying in 3s"; sleep 3;
              git fetch origin main && git pull --rebase origin main || true;
            done
          fi
