name: Trivy Security Scan

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy FS scan (vulnerabilities + secrets)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          security-checks: vuln,secret,config
          exit-code: '0' # non-blocking initially
          format: 'table'
          ignore-unfixed: true
          vuln-type: 'os,library'
      - name: Run Trivy config scan (IaC)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          exit-code: '0'
          format: 'table'
          severity: 'CRITICAL,HIGH'
